# render.yaml for ScanSphere project
# This file defines how Render will build and deploy your services.

services:
  - type: web
    name: scansphere-backend
    env: node
    rootDir: Finalproject/abc/node-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://parthgote:whC50ms9WaGP8S8A@cluster0.fclyu.mongodb.net/Scansphere" # Replace with your actual MongoDB Atlas URI
      - key: PORT
        value: 5001 # Or desired port for backend
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: "Sujaloswal@123" # Replace with a strong, random secret
    healthCheckPath: /api/health

  - type: web
    name: scansphere-frontend
    env: python
    rootDir: Finalproject/abc
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_SECRET_KEY
        value: "brain_tumor_detection_fallback_secret_key" # Replace with a strong, random secret
      - key: OPENAI_API_KEY
        sync: false # Set this in the Render dashboard for security
      - key: PORT
        value: 5000 # Or desired port for frontend (Flask)
    healthCheckPath: / 